PARAKEET_SAMPLE_RATE = 16000

PARAKEET_SAMPLE_MINUTE = PARAKEET_SAMPLE_RATE * 60

PARAKEET_MODEL_MAX_DURATION_MIN = 24

PARAKEET_MODEL_MAX_DURATION_KHZ = (
    PARAKEET_MODEL_MAX_DURATION_MIN * PARAKEET_SAMPLE_MINUTE
)
