PARAKEET_MODEL_REF = "nvidia/parakeet-tdt-0.6b-v3"

PARAKEET_SAMPLE_RATE = 16000

PARAKEET_SAMPLE_MINUTE = PARAKEET_SAMPLE_RATE * 60

PARAKEET_INFERENCE_MAX_DURATION_MIN = 24

PARAKEET_INFERENCE_MAX_DURATION_KHZ = (
    PARAKEET_INFERENCE_MAX_DURATION_MIN * PARAKEET_SAMPLE_MINUTE
)

PARAKEET = "parakeet"

WHISPER_CPP = "whisper-cpp"

DEVICE_CPU = "cpu"

DEVICE_GPU = "gpu"

DEVICE_MPS = "mps"
