name: pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v6
    - name: Setup Python project
      uses: actions/setup-python@v6
      with:
        python-version-file: "caul/pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.9.24"
        python-version-file: "caul/pyproject.toml"
        enable-cache: true
    - name: Analysing the code with pylint
      run: |
        cd caul
        uv run --extra preprocessing --extra nemo --extra pyannote --extra fireredasr2 --extra faster_whisper --frozen pylint $(git ls-files '*.py')
