name: test

on:
  push:
    branches: ['main']
  pull_request:
    paths:
      - '**.py'
      - '.github/workflows/test.yml'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Python project
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.24"
          python-version: "3.13"
          enable-cache: true
      - name: Install deps
        run: |
          uv sync --all-extras --dev
      - name: Install torchcodec deps
        run: sudo apt update && sudo apt install -y ffmpeg
      - name: Run tests
        run: |
          uv run --dev --all-extras --frozen pytest -vvv --cache-clear --show-capture=all -r A test
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true